using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

// --- 1. Service Registration ---

// Add support for Controllers (Required if you use Controller classes)
builder.Services.AddControllers();

// Add OpenAPI document generation (The .NET 9+ way)
builder.Services.AddOpenApi();

// Register ApplicationDbContext with SQL Server
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

// Define the "AllowAll" CORS policy
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll",
        policy => policy.AllowAnyOrigin()
                        .AllowAnyMethod()
                        .AllowAnyHeader());
});

var app = builder.Build();

// --- 2. Middleware Pipeline ---

if (app.Environment.IsDevelopment())
{
    // Generates the openapi/v1.json document
    app.MapOpenApi();

    // Serves the interactive Swagger UI at /swagger
    app.UseSwaggerUI(options =>
    {
        // This must point to the document generated by MapOpenApi
        options.SwaggerEndpoint("/openapi/v1.json", "v1");
    });
}

app.UseHttpsRedirection();

// Enable the CORS policy globally
app.UseCors("AllowAll");

// Map your controller routes
app.MapControllers();

// --- 3. Run Application ---

app.Run();